language: node_js
node_js:
  - stable
cache: yarn
script: skip

after_success:
  - npm run test:coveralls
  - npm run build:storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: storybook-static
  on:
    branch: release

notifications:
  email:
    on_success: never
    on_failure: never
